name: Build and Release Nezumi
run-name: Build and Release Nezumi
on: 
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: 'Version of Nezumi to build and release'
        required: true
      notes:
        type: string
        description: 'Notes for this release'
        required: false
        
permissions:
  contents: write
        
jobs:
  Build-and-Release-Nezumi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout  
        uses: actions/checkout@v4
      - name: Setup .NET 
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Build  
        run: dotnet build -c Release
      - name: Publish  
        run: dotnet publish -o ./ -c Release /p:AssemblyVersion=${{ inputs.version }} /p:Version=${{ inputs.version }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Nezumi
          path: ./Nezumi.exe
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ inputs.version }}
          name: Release ${{ inputs.version }}
          body: ${{ inputs.notes }}
          draft: false
          prerelease: false
          generate_release_notes: true
          make_latest: true
          files: './Nezumi.exe'
